name=TrinityLED
version=1.0.0
author=Ask Blommaert <ask.blommaert@gmail.com>
maintainer=Ask Blommaert <ask.blommaert@gmail.com>
sentence=Effects library for LED strips.
paragraph=Effects library for LED strips.
category=Control
url=https://github.com/your-username/your-library-name
architectures=*
depends=FastLED